"""initial schema

Revision ID: cffe56eb22a1
Revises:
Create Date: 2026-10-08 01:24:09.616717+00:00

Every table from the Database Design. Written by hand from the autogenerated
draft: enum columns are VARCHAR(32) with one named CHECK each, which is what the
models create (backend/app/models/columns.py). Like every migration, this file
is frozen: it never imports the app, so later model changes cannot alter it.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import SchemaItem

revision: str = "cffe56eb22a1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _id_and_owner() -> list[sa.Column[object]]:
    return [
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
    ]


def _created_at() -> sa.Column[object]:
    return sa.Column(
        "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    )


def _timestamps() -> list[sa.Column[object]]:
    return [
        _created_at(),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    ]


def _owned(table: str) -> list[SchemaItem]:
    """Primary key, ``UNIQUE (user_id, id)``, and the cascade from users."""
    return [
        sa.PrimaryKeyConstraint("id", name=f"pk_{table}"),
        sa.UniqueConstraint("user_id", "id", name=f"uq_{table}_user_id_id"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=f"fk_{table}_user_id_users", ondelete="CASCADE"
        ),
    ]


def _tenant_fk(table: str, column: str, parent: str, ondelete: str) -> sa.ForeignKeyConstraint:
    """``(user_id, column)`` references ``parent (user_id, id)``."""
    if ondelete == "SET NULL":
        ondelete = f"SET NULL ({column})"
    return sa.ForeignKeyConstraint(
        ["user_id", column],
        [f"{parent}.user_id", f"{parent}.id"],
        name=f"fk_{table}_user_id_{column}_{parent}",
        ondelete=ondelete,
    )


def _enum(table: str, column: str, values: Sequence[str]) -> list[SchemaItem]:
    """A VARCHAR(32) column limited to ``values``."""
    allowed = ", ".join(f"'{value}'" for value in values)
    return [
        sa.Column(column, sa.String(32), nullable=False),
        _check(table, column, f"{column} IN ({allowed})"),
    ]


# CHECK names go through op.f() ("already final"): otherwise op applies the
# naming convention again and the name becomes ck_<table>_ck_<table>_<name>.
def _check(table: str, name: str, condition: str) -> sa.CheckConstraint:
    return sa.CheckConstraint(condition, name=op.f(f"ck_{table}_{name}"))


def _name_column(table: str) -> list[SchemaItem]:
    return [
        sa.Column("name", sa.String(100), nullable=False),
        _check(table, "name_not_blank", "btrim(name) <> ''"),
    ]


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=True),
        sa.Column("timezone", sa.String(64), server_default="UTC", nullable=False),
        sa.Column(
            "no_deadline_goal_share_bps", sa.Integer(), server_default="2000", nullable=False
        ),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        _check("users", "email_lowercase", "email = lower(email)"),
        _check("users", "email_not_blank", "email <> ''"),
        _check("users", "goal_share_bps_range", "no_deadline_goal_share_bps BETWEEN 0 AND 10000"),
    )

    op.create_table(
        "refresh_tokens",
        *_id_and_owner(),
        sa.Column("token_hash", sa.String(128), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        *_timestamps(),
        *_owned("refresh_tokens"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
        _tenant_fk("refresh_tokens", "replaced_by_id", "refresh_tokens", "SET NULL"),
    )
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"])

    op.create_table(
        "income_sources",
        *_id_and_owner(),
        *_name_column("income_sources"),
        sa.Column("expected_amount_cents", sa.BigInteger(), nullable=False),
        *_enum(
            "income_sources", "pay_frequency", ["weekly", "biweekly", "semi_monthly", "monthly"]
        ),
        sa.Column("anchor_date", sa.Date(), nullable=True),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("second_day_of_month", sa.Integer(), nullable=True),
        *_timestamps(),
        *_owned("income_sources"),
        _check("income_sources", "expected_amount_positive", "expected_amount_cents > 0"),
        _check("income_sources", "day_of_month_range", "day_of_month BETWEEN 1 AND 31"),
        _check(
            "income_sources",
            "second_day_of_month_range",
            "second_day_of_month BETWEEN 1 AND 31",
        ),
        _check(
            "income_sources",
            "schedule_parameters",
            "(pay_frequency IN ('weekly', 'biweekly')"
            " AND anchor_date IS NOT NULL"
            " AND day_of_month IS NULL AND second_day_of_month IS NULL)"
            " OR (pay_frequency = 'semi_monthly'"
            " AND anchor_date IS NULL"
            " AND day_of_month IS NOT NULL AND second_day_of_month IS NOT NULL"
            " AND day_of_month < second_day_of_month)"
            " OR (pay_frequency = 'monthly'"
            " AND anchor_date IS NULL"
            " AND day_of_month IS NOT NULL AND second_day_of_month IS NULL)",
        ),
    )

    op.create_table(
        "paychecks",
        *_id_and_owner(),
        sa.Column("income_source_id", sa.Uuid(), nullable=False),
        sa.Column("pay_date", sa.Date(), nullable=False),
        sa.Column("expected_amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("actual_amount_cents", sa.BigInteger(), nullable=True),
        *_timestamps(),
        *_owned("paychecks"),
        _tenant_fk("paychecks", "income_source_id", "income_sources", "RESTRICT"),
        sa.UniqueConstraint(
            "income_source_id", "pay_date", name="uq_paychecks_income_source_id_pay_date"
        ),
        _check("paychecks", "expected_amount_positive", "expected_amount_cents > 0"),
        _check("paychecks", "actual_amount_not_negative", "actual_amount_cents >= 0"),
    )

    op.create_table(
        "bills",
        *_id_and_owner(),
        *_name_column("bills"),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("first_due_date", sa.Date(), nullable=False),
        sa.Column("repeat_every_months", sa.Integer(), nullable=True),
        *_timestamps(),
        *_owned("bills"),
        _check("bills", "amount_positive", "amount_cents > 0"),
        _check("bills", "priority_positive", "priority >= 1"),
        _check("bills", "repeat_every_months_positive", "repeat_every_months >= 1"),
    )

    op.create_table(
        "bill_payments",
        *_id_and_owner(),
        sa.Column("bill_id", sa.Uuid(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        *_timestamps(),
        *_owned("bill_payments"),
        _tenant_fk("bill_payments", "bill_id", "bills", "CASCADE"),
        _check("bill_payments", "amount_positive", "amount_cents > 0"),
    )
    op.create_index("ix_bill_payments_bill_id_due_date", "bill_payments", ["bill_id", "due_date"])

    op.create_table(
        "essential_expenses",
        *_id_and_owner(),
        *_name_column("essential_expenses"),
        sa.Column("amount_per_period_cents", sa.BigInteger(), nullable=False),
        *_timestamps(),
        *_owned("essential_expenses"),
        _check("essential_expenses", "amount_per_period_positive", "amount_per_period_cents > 0"),
    )

    op.create_table(
        "debts",
        *_id_and_owner(),
        *_name_column("debts"),
        sa.Column("balance_cents", sa.BigInteger(), nullable=False),
        sa.Column("apr_bps", sa.Integer(), nullable=False),
        sa.Column("minimum_payment_cents", sa.BigInteger(), nullable=False),
        sa.Column("due_day", sa.Integer(), nullable=False),
        *_timestamps(),
        *_owned("debts"),
        _check("debts", "balance_not_negative", "balance_cents >= 0"),
        _check("debts", "apr_bps_not_negative", "apr_bps >= 0"),
        _check("debts", "minimum_payment_not_negative", "minimum_payment_cents >= 0"),
        _check("debts", "due_day_range", "due_day BETWEEN 1 AND 31"),
    )

    op.create_table(
        "goals",
        *_id_and_owner(),
        *_name_column("goals"),
        *_enum("goals", "kind", ["emergency", "savings", "purchase"]),
        sa.Column("target_cents", sa.BigInteger(), nullable=False),
        sa.Column("current_cents", sa.BigInteger(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        *_timestamps(),
        *_owned("goals"),
        _check("goals", "target_positive", "target_cents > 0"),
        _check("goals", "current_not_negative", "current_cents >= 0"),
        _check("goals", "priority_positive", "priority >= 1"),
    )
    op.create_index(
        "ix_goals_one_emergency_per_user",
        "goals",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'emergency'"),
    )

    op.create_table(
        "reserves",
        *_id_and_owner(),
        *_enum("reserves", "kind", ["bill", "goal", "debt"]),
        sa.Column("bill_id", sa.Uuid(), nullable=True),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("debt_id", sa.Uuid(), nullable=True),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        *_timestamps(),
        *_owned("reserves"),
        _tenant_fk("reserves", "bill_id", "bills", "CASCADE"),
        _tenant_fk("reserves", "goal_id", "goals", "CASCADE"),
        _tenant_fk("reserves", "debt_id", "debts", "CASCADE"),
        sa.UniqueConstraint("bill_id", name="uq_reserves_bill_id"),
        sa.UniqueConstraint("goal_id", name="uq_reserves_goal_id"),
        sa.UniqueConstraint("debt_id", name="uq_reserves_debt_id"),
        _check("reserves", "amount_not_negative", "amount_cents >= 0"),
        _check(
            "reserves",
            "target_matches_kind",
            "(kind = 'bill' AND bill_id IS NOT NULL AND goal_id IS NULL AND debt_id IS NULL)"
            " OR (kind = 'goal' AND goal_id IS NOT NULL AND bill_id IS NULL AND debt_id IS NULL)"
            " OR (kind = 'debt' AND debt_id IS NOT NULL AND bill_id IS NULL AND goal_id IS NULL)",
        ),
    )

    op.create_table(
        "balance_snapshots",
        *_id_and_owner(),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        *_timestamps(),
        *_owned("balance_snapshots"),
    )
    op.create_index("ix_balance_snapshots_user_id_as_of", "balance_snapshots", ["user_id", "as_of"])

    op.create_table(
        "paycheck_plans",
        *_id_and_owner(),
        sa.Column("paycheck_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        *_enum("paycheck_plans", "status", ["draft", "committed", "superseded"]),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("engine_version", sa.String(32), nullable=False),
        sa.Column("input_hash", sa.CHAR(64), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("next_pay_date", sa.Date(), nullable=False),
        sa.Column("paycheck_amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("available_balance_cents", sa.BigInteger(), nullable=False),
        sa.Column("safe_to_spend_cents", sa.BigInteger(), nullable=False),
        sa.Column("reserve_deficit_cents", sa.BigInteger(), nullable=False),
        *_timestamps(),
        *_owned("paycheck_plans"),
        _tenant_fk("paycheck_plans", "paycheck_id", "paychecks", "RESTRICT"),
        sa.UniqueConstraint("paycheck_id", "version", name="uq_paycheck_plans_paycheck_id_version"),
        _check("paycheck_plans", "version_positive", "version >= 1"),
        _check(
            "paycheck_plans",
            "committed_at_matches_status",
            "(status <> 'draft' OR committed_at IS NULL)"
            " AND (status <> 'committed' OR committed_at IS NOT NULL)",
        ),
        _check("paycheck_plans", "input_hash_sha256_hex", "input_hash ~ '^[0-9a-f]{64}$'"),
        _check("paycheck_plans", "paycheck_amount_not_negative", "paycheck_amount_cents >= 0"),
        _check("paycheck_plans", "safe_to_spend_not_negative", "safe_to_spend_cents >= 0"),
        _check("paycheck_plans", "reserve_deficit_not_negative", "reserve_deficit_cents >= 0"),
    )
    op.create_index(
        "ix_paycheck_plans_one_committed_per_paycheck",
        "paycheck_plans",
        ["paycheck_id"],
        unique=True,
        postgresql_where=sa.text("status = 'committed'"),
    )

    op.create_table(
        "allocations",
        *_id_and_owner(),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        *_enum(
            "allocations",
            "tier",
            ["bill", "essential", "debt_minimum", "emergency_fund", "goal"],
        ),
        sa.Column("bill_id", sa.Uuid(), nullable=True),
        sa.Column("essential_expense_id", sa.Uuid(), nullable=True),
        sa.Column("debt_id", sa.Uuid(), nullable=True),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("requested_cents", sa.BigInteger(), nullable=False),
        sa.Column("funded_cents", sa.BigInteger(), nullable=False),
        *_enum(
            "allocations",
            "reason",
            [
                "bill_due",
                "essential",
                "essential_prorated",
                "debt_minimum",
                "debt_payoff",
                "emergency_fund",
                "goal_deadline",
                "goal_no_deadline",
                "goal_deadline_passed",
            ],
        ),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("total_cents", sa.BigInteger(), nullable=False),
        sa.Column("set_aside_cents", sa.BigInteger(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("paychecks", sa.Integer(), nullable=True),
        sa.Column("days_covered", sa.Integer(), nullable=True),
        sa.Column("days_in_period", sa.Integer(), nullable=True),
        sa.Column("share_bps", sa.Integer(), nullable=True),
        _created_at(),
        *_owned("allocations"),
        _tenant_fk("allocations", "plan_id", "paycheck_plans", "CASCADE"),
        _tenant_fk("allocations", "bill_id", "bills", "SET NULL"),
        _tenant_fk("allocations", "essential_expense_id", "essential_expenses", "SET NULL"),
        _tenant_fk("allocations", "debt_id", "debts", "SET NULL"),
        _tenant_fk("allocations", "goal_id", "goals", "SET NULL"),
        sa.UniqueConstraint("plan_id", "position", name="uq_allocations_plan_id_position"),
        _check("allocations", "position_not_negative", "position >= 0"),
        _check("allocations", "requested_positive", "requested_cents > 0"),
        _check(
            "allocations", "funded_range", "funded_cents >= 0 AND funded_cents <= requested_cents"
        ),
        _check("allocations", "total_not_negative", "total_cents >= 0"),
        _check("allocations", "set_aside_not_negative", "set_aside_cents >= 0"),
        _check("allocations", "paychecks_positive", "paychecks >= 1"),
        _check("allocations", "days_covered_not_negative", "days_covered >= 0"),
        _check("allocations", "days_in_period_positive", "days_in_period >= 1"),
        _check("allocations", "share_bps_range", "share_bps BETWEEN 0 AND 10000"),
        _check(
            "allocations",
            "target_matches_tier",
            "(tier = 'bill'"
            " AND essential_expense_id IS NULL AND debt_id IS NULL AND goal_id IS NULL)"
            " OR (tier = 'essential'"
            " AND bill_id IS NULL AND debt_id IS NULL AND goal_id IS NULL)"
            " OR (tier = 'debt_minimum'"
            " AND bill_id IS NULL AND essential_expense_id IS NULL AND goal_id IS NULL)"
            " OR (tier IN ('emergency_fund', 'goal')"
            " AND bill_id IS NULL AND essential_expense_id IS NULL AND debt_id IS NULL)",
        ),
    )

    op.create_table(
        "goal_projections",
        *_id_and_owner(),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("contribution_cents", sa.BigInteger(), nullable=False),
        sa.Column("still_needed_cents", sa.BigInteger(), nullable=False),
        sa.Column("projected_date", sa.Date(), nullable=True),
        *_enum(
            "goal_projections",
            "status",
            ["complete", "on_track", "behind", "no_deadline", "deadline_passed"],
        ),
        _created_at(),
        *_owned("goal_projections"),
        _tenant_fk("goal_projections", "plan_id", "paycheck_plans", "CASCADE"),
        _tenant_fk("goal_projections", "goal_id", "goals", "SET NULL"),
        sa.UniqueConstraint("plan_id", "position", name="uq_goal_projections_plan_id_position"),
        sa.UniqueConstraint("plan_id", "goal_id", name="uq_goal_projections_plan_id_goal_id"),
        _check("goal_projections", "position_not_negative", "position >= 0"),
        _check("goal_projections", "contribution_not_negative", "contribution_cents >= 0"),
        _check("goal_projections", "still_needed_not_negative", "still_needed_cents >= 0"),
    )


def downgrade() -> None:
    # Reverse dependency order; dropping a table drops its indexes and constraints.
    for table in (
        "goal_projections",
        "allocations",
        "paycheck_plans",
        "balance_snapshots",
        "reserves",
        "goals",
        "debts",
        "essential_expenses",
        "bill_payments",
        "bills",
        "paychecks",
        "income_sources",
        "refresh_tokens",
        "users",
    ):
        op.drop_table(table)
